flechaIzquierda = keyboard_check(vk_left);
flechaDerecha = keyboard_check(vk_right);
flechaArriba = keyboard_check(vk_up);
flechaAbajo = keyboard_check(vk_down);
teclaSalto = keyboard_check_pressed(ord("Z"));
teclaDisparo = keyboard_check_pressed(ord("X"));
scr_EstadosJugador();
sprite_index = sprite;
x += velocidadHorizontal;
y += velocidadVertical;